dist: xenial

matrix:
  include:
    # -------------------- GCC + SonarCloud --------------------
    - language: cpp
      addons:
        sonarcloud:
          organization: pavel-kirienko
          token:
            secure: "IrmNvn9Blg3u/4VlX87qAvukl3deX847tfUAqNrkz3Tu8YW8u+fnitt6J/2gtnhW+cy57CM/wkWU2BIvIjRINbWLJle1KlnB4isdrmRu8Nhk57+uww/w4599UIiAjo6m50Fa7lvVAMR5wR+ZkD4SV7NDDAR6R/gqEqwuIyyXh9mrvCVgQyt+inQPgg4vG6bLPg9TXXXQ/U9+5LgKgCEyV703slzznv2oZJMzcbzT1fdnkcW2veIKTSByB1BqyKseabUZ3qgEGzozk7jV4lp3sRjfVu75F5bTOtB40f6fcOCVlk0FR26HtnFOylXzQ4uCJoNyHWz60gGmYpBi8dgY4wEN/ShsWG4bm0DPaR9EICQagVBCKk1GqGZ3FCBhRTvKtNL0jMFxb05YFDHRlGijEXhGKdmEKextMb4Q7SI4GjRzYuFOmzHIkJnLZPNmQgZa9qZlTGYXXupYAqxUhDi5euyeInaXd+uLWSajoLiCyKioXMOYb69LnswttWkhjjHa+a7OOI1pw/Tf6mzztNZ/l19m9ap85aiC+ysKc1+zakNXyECqezPMdJUuDdiB+OKhXlW8wAGni07VhulKxALbqop86owNkQI85dArSpKX4vrzwhx5ZnNSvvNQL9iFZsQgxD7WI9dLa4RG2FoIMoal86eZvXnePXOtWpLWJy+kaV4="
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - g++-9-multilib
            - gcc-9-multilib
            - linux-libc-dev:i386
      script:
        - CC=gcc-9 && CXX=g++-9 && cmake tests
        - build-wrapper-linux-x86-64 --out-dir sonar-dump make all  # The build wrapper comes from Sonar Cloud.
        - sh run_all_tests.sh
        - sonar-scanner

    # -------------------- Clang 9 --------------------
    - language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-7-dev:i386
            - linux-libc-dev:i386
            - libc6-dev-i386
      script:
        - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 9
        - clang++-9 -E -x c++ - -v < /dev/null    # Print the Clang configuration for troubleshooting purposes
        - cmake -DCMAKE_C_COMPILER=clang-9 -DCMAKE_CXX_COMPILER=clang++-9 tests
        - make
        - sh run_all_tests.sh

    # -------------------- Static analysis --------------------
    - language: cpp
      script:
        - sudo rm -rf /usr/local/clang*
        - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 9
        - sudo apt install clang-format-9 clang-tidy-9
        - sudo ln -sf $(which clang-format-9) /usr/bin/clang-format
        - sudo ln -sf $(which clang-tidy-9) /usr/bin/clang-tidy

        # Static analysis.
        - scripts/run_static_analysis.sh

        # Code style enforcement.
        - scripts/format.sh
        - 'modified="$(git status --porcelain --untracked-files=no)"'
        - 'if [ -n "$modified" ]; then echo "Run scripts/format.sh to reformat the code."; exit 1; fi'

git:
  depth: false  # Disable shallow clone because it is incompatible with SonarCloud
