dist: xenial

matrix:
  include:
    # -------------------- GCC + SonarCloud --------------------
#    - language: cpp
#      addons:
#        sonarcloud:
#          organization: uavcan
#          token:
#            secure: "LbaAOcguJspiraxAb9RNkwtGvWDh1aMTEPdz2MCbeICxIIiJ6LRoabD58rLvPsrNSWsR3AAep9Q551dDzT8c04UX+C67N3CZ/oof4DwBT+XQCSfB8FMj2QpbglJqwFPclYUorROjH31VwGcgIq3kfQq3Cw8G+nsL8vRaaJXsJb/KPp6MU698NGzHJIgRyn29VW76dW0NSxOv4ub3e6aKOnwfI+h1Ctx4p3hCdzd402PaZspv1VgEmirf5sVUJvE67PVIzlwov+CF+2PlrIpGUWI98Gl6HqYHv3hkvSP+4iLvCMD99Zmee4yLnCFY3xcJuZ8zKCRBBoquuUxdzK0f/4l9TZXePDXDMhaj3cXLlaAPWDw+emqTcm+hzP1mt/DaIqopAf54bQojVWELbL6QcjBNkphSvWBeIoyKWuUWU2LWJcJNPXFNUug//D99uXNurkzAIWR+lcsx6zO+cr4EN00N92W6hPt7mhKCF0prs7SvMleEi9mAbxvd4lOHFT56RvcB5ny6IapX9/q1+xm5iSoAzLhbvU1aUCnX74S/yFFejvClxxhW+P0bXYNtZ9RRfl8BdSgENTgA9RSnqdtIJGA4cU3OxIHDyJIC2cgmsE38u7QaMO49r1liJFH+xmDPa6bkGGHiPoHaPu9+g+wYFttK9FNt5ozyHY+VpjwTrY4="
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-9
#            - g++-9-multilib
#            - gcc-9-multilib
#            - linux-libc-dev:i386
#      script:
#        - CC=gcc-9 && CXX=g++-9 && cmake tests
#        - build-wrapper-linux-x86-64 --out-dir sonar-dump make all  # The build wrapper comes from Sonar Cloud.
#        - ./run_tests --rng-seed time
#        - sonar-scanner

    # -------------------- Clang 9 --------------------
#    - language: cpp
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - libstdc++-7-dev:i386
#            - linux-libc-dev:i386
#            - libc6-dev-i386
#      script:
#        - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 9
#        - clang++-9 -E -x c++ - -v < /dev/null    # Print the Clang configuration for troubleshooting purposes
#        - cmake -DCMAKE_C_COMPILER=clang-9 -DCMAKE_CXX_COMPILER=clang++-9 tests
#        - make
#        - ./run_tests --rng-seed time

    # -------------------- Static analysis --------------------
    - language: cpp
      script:
        - sudo rm -rf /usr/local/clang*
        - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 9
        - sudo apt install clang-format-9 clang-tidy-9
        - sudo ln -sf $(which clang-format-9) /usr/bin/clang-format
        - sudo ln -sf $(which clang-tidy-9) /usr/bin/clang-tidy

        # Static analysis.
        - scripts/run_static_analysis.sh

        # Code style enforcement.
        - scripts/format.sh
        - 'modified="$(git status --porcelain --untracked-files=no)"'
        - 'if [ -n "$modified" ]; then echo "Run scripts/format.sh to reformat the code."; exit 1; fi'

git:
  depth: false  # Disable shallow clone because it is incompatible with SonarCloud
